### ISSUE TITLE
关于波形显示横轴缩放的问题

### ISSUE THREAD

**Issue by ZenghuiJIA** [liuhao1946/rtt_t2#2]
大佬现在的开发框架是基于QT的吗，现在的波形显示只能进行y轴的滚轮缩放，对于查看细节的x轴没有相关的操作说明，请问支持x轴缩放吗，如果不支持的话后面有没有计划。

**Comment by lh-hg** [comment]
不好意思，没有留意。支持x轴缩放，参看下图。
![rtt_t2_l7S8PeoaXJ](https://github.com/user-attachments/assets/2f9924ae-b632-44f4-b050-d2567004e973)

它的操作没有缩放y那么方便，后续会考虑让x轴缩放更简单

**Comment by ZenghuiJIA** [comment]
好的感谢回复。
